name: CI

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3']
        wp: ['latest', '5.3']
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extension-csv: mbstring, intl #optional, setup extensions
        ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        pecl: false #optional, setup PECL

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install --optimize-autoloader --prefer-dist

    - name: Install WP Tests
      env:
        WP_VERSION: ${{ matrix.wp }}
      run: bash bin/install-wp-tests.sh wordpress_test root root mysql $WP_VERSION

    - name: phpunit tests
      run: ./vendor/bin/phpunit
